In [ ]:
import numpy as np

In [ ]:
my_cs1 = [80, 85, 90, 95]

my_cs2 = np.array(my_cs1)
my_cs2

array([80, 85, 90, 95])

In [ ]:
my_cs2 = [60, 70, 80, 90]

my_arrayBCS = [my_cs1, my_cs2]
my_arrayBCS

[[80, 85, 90, 95], [60, 70, 80, 90]]

In [ ]:
my_arrayCS2 = np.array([my_arrayBCS])
my_arrayCS2

array([[[80, 85, 90, 95],
        [60, 70, 80, 90]]])

In [ ]:
my_arrayCS2.shape

(1, 2, 4)

In [ ]:
my_arrayCS2.dtype

dtype('int64')

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [ ]:
array1 = np.array([[5, 15, 20, 25], [10, 20, 30, 40]])
array1

array([[ 5, 15, 20, 25],
       [10, 20, 30, 40]])

In [ ]:
array1*array1

array([[  25,  225,  400,  625],
       [ 100,  400,  900, 1600]])

In [ ]:
array1+array1

array([[10, 30, 40, 50],
       [20, 40, 60, 80]])

In [ ]:
1 / array1

array([[0.2       , 0.06666667, 0.05      , 0.04      ],
       [0.1       , 0.05      , 0.03333333, 0.025     ]])

In [ ]:
1 / 1 + 2.71828 **

In [ ]:
array1 ** 3

array([[  125,  3375,  8000, 15625],
       [ 1000,  8000, 27000, 64000]])

In [ ]:
my_ex1 = [5, 15, 25, 35]
my_ex1

[5, 15, 25, 35]

In [ ]:
my_ex2 = [7, 14, 21, 28]
my_ex2

[7, 14, 21, 28]

In [ ]:
arrays = np.array([[5, 15, 25, 35], [7, 14, 21, 28]])
arrays

array([[ 5, 15, 25, 35],
       [ 7, 14, 21, 28]])

In [ ]:
arrays + arrays

array([[10, 30, 50, 70],
       [14, 28, 42, 56]])

In [ ]:
np.arange(9, 90, 3)

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87])

In [ ]:
arrays.dtype

dtype('int64')

In [ ]:
arrays.shape

(2, 4)

In [ ]:
import numpy as np

array = np.arange(50)
array = array.reshape(10,5)

In [ ]:
array.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [ ]:
array_2 = np.arange(50)
array_2.reshape(5, 5, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])